name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs_on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Xcode
      run: sudo xcode-select -s '/Applications/Xcode.app/Contents/Developer'

    - name: Build app
      run: xcodebuild -scheme TrackpadAir -project TrackpadAir.xcodeproj build 

    - name: Archive app
      run: xcodebuild -scheme TrackpadAir -project TrackpadAir.xcodeproj archive -archivePath TrackpadAir.xcarchive 

    - name: Unzip .app file from Archive
      run: |
        cd TrackpadAir.xcarchive/Products/Applications
        zip -r TrackpadAir.app.zip TrackpadAir.app
        mv TrackpadAir.app.zip ../../../
        
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }} 
        asset_path: ./TrackpadAir.app.zip
        asset_name: TrackpadAir.app.zip
        asset_content_type: application/zip
